<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'admin',
                'last_name' => '',
                'email' => 'admin@admin.com',
                'password' => bcrypt('admin'),
                'rank' => 'admin',
				'avatar' => 'placeholder.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => 'lDlvLM7FPzTZ41BLsDsaYagCAtvvWRSWubaImui1NzxWtsq8M8i12DbPlFuS',
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Nathanaël',
                'last_name' => 'Langlois',
                'email' => 'nathanael.langlois@liigem.io',
                'password' => bcrypt('nathanael'),
                'rank' => 'user',
				'avatar' => 'placeholder.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => 'vcOQpAfkEIFlZnKPWdVwnZF8RPL0SSQWU2z3pqoYZFoiHS2iMfoOo1RVD9pI',
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Professeur',
                'last_name' => 'Tournesol',
                'email' => 'professeur@tournesol.com',
                'password' => bcrypt('tournesol'),
                'rank' => 'user',
				'avatar' => 'placeholder.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Pierre',
                'last_name' => 'Chatelanaz',
                'email' => 'pierre.chatelanaz@liigem.io',
                'password' => bcrypt('pierre'),
                'rank' => 'student',
				'avatar' => '/images/students/1.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => 'iUYVnGEbSOXzdR0CMS2p3J8MHrzWyxu5M9hqo5aQuaQbyPAYiZrhRW12dq0E',
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Fabien',
                'last_name' => 'Delattre',
                'email' => 'fabien.delattre@liigem.io',
                'password' => bcrypt('fabien'),
                'rank' => 'student',
				'avatar' => '/images/students/2.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'Ulysse',
                'last_name' => 'Arnaud',
                'email' => 'ulysse.arnaud@liigem.io',
                'password' => bcrypt('ulysse'),
                'rank' => 'student',
				'avatar' => '/images/students/3.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'Simon',
                'last_name' => 'Lecoq',
                'email' => 'simon.lecoq@liigem.io',
                'password' => bcrypt('simon'),
                'rank' => 'student',
				'avatar' => '/images/students/4.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Baptiste',
                'last_name' => 'Raabe',
                'email' => 'baptiste.raabe@liigem.io',
                'password' => '$2y$10$KhoHr3ZBu9g17THGZcacDuK0UHpq4Vaoky5N0D.EqXOl7EReoe25.',
                'rank' => 'student',
				'avatar' => '/images/students/5.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => bcrypt('baptiste'),
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'Agathe',
                'last_name' => 'Plourde',
                'email' => 'agathe@plourde.fr',
                'password' => '$2a$04$sXpDv4KpFlD3XXGB7o0h/u58Ps0oSX304uiQj0OoHBAdHzVTsd8wC',
                'rank' => 'student',
				'avatar' => '/images/students/7.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => '2017-03-19 00:00:00',
                'updated_at' => '2017-03-19 00:00:00',
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Philippine',
                'last_name' => 'Marceau',
                'email' => 'phil.marceau@liigem.io',
                'password' => '$2a$04$sXpDv4KpFlD3XXGB7o0h/u58Ps0oSX304uiQj0OoHBAdHzVTsd8wC',
                'rank' => 'student',
				'avatar' => '/images/students/8.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => '2017-03-19 00:00:00',
                'updated_at' => '2017-03-19 00:00:00',
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Émile',
                'last_name' => 'Desruisseaux',
                'email' => 'emile@desruisseaux.fr',
                'password' => '$2a$04$sXpDv4KpFlD3XXGB7o0h/u58Ps0oSX304uiQj0OoHBAdHzVTsd8wC',
                'rank' => 'student',
				'avatar' => '/images/students/9.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => '2017-03-19 00:00:00',
                'updated_at' => '2017-03-19 00:00:00',
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'Océane',
                'last_name' => 'Laliberté',
                'email' => 'oceane@laliberte.fr',
                'password' => '$2a$04$sXpDv4KpFlD3XXGB7o0h/u58Ps0oSX304uiQj0OoHBAdHzVTsd8wC',
                'rank' => 'student',
				'avatar' => '/images/students/10.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => '2017-03-19 00:00:00',
                'updated_at' => '2017-03-19 00:00:00',
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Zara',
                'last_name' => 'Lang',
                'email' => 'zara@lang.com',
                'password' => '$2a$04$sXpDv4KpFlD3XXGB7o0h/u58Ps0oSX304uiQj0OoHBAdHzVTsd8wC',
                'rank' => 'student',
				'avatar' => '/images/students/11.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => '2017-03-19 00:00:00',
                'updated_at' => '2017-03-19 00:00:00',
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'David',
                'last_name' => 'Bourgouin',
                'email' => 'david33@liigem.io',
                'password' => '$2a$04$sXpDv4KpFlD3XXGB7o0h/u58Ps0oSX304uiQj0OoHBAdHzVTsd8wC',
                'rank' => 'student',
				'avatar' => '/images/students/6.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
				'ip_register' => '178.62.0.77',
				'ip_last' => '178.62.0.77',
                'created_at' => '2017-03-19 00:00:00',
                'updated_at' => '2017-03-19 00:00:00',
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'Ashok',
                'last_name' => 'Deb',
                'email' => 'jobeditions@gmail.com',
                'password' => bcrypt('ashokadev'),
                'rank' => 'student',
                'avatar' => 'placeholder.jpg',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'remember_token' => NULL,
                'ip_register' => '178.62.0.77',
                'ip_last' => '178.62.0.77',
                'created_at' => '2017-03-19 00:00:00',
                'updated_at' => '2017-03-19 00:00:00',
            ),
        ));


    }
}
